version: '3.7'

services:
  postgres:
    image: 'postgres:12-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    image: whale
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
      - 'node_modules:/app/node_modules'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    image: whale
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
      - 'node_modules:/app/node_modules'
    env_file:
      - '.env'

  cable:
    depends_on:
      - 'redis'
    image: whale
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
      - 'node_modules:/app/node_modules'
    env_file:
      - '.env'

  webpack:
    image: whale
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
      - 'node_modules:/app/node_modules'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
  node_modules:
  bundle:
